# Generated by Django 2.2 on 2020-05-19 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20200519_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='Votes_total',
            field=models.IntegerField(),
        ),
    ]
