# Generated by Django 2.2 on 2020-05-19 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20200519_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='Votes',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default='3'),
        ),
    ]
